name: Deploy to Github pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Green IT Analysis"]
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book